version: '3.8'
services:
  postgres:
    image: postgres
    container_name: mylibrary_postgres
    environment:
      POSTGRES_USER: mylibrary_user
      POSTGRES_PASSWORD: mylibrary_password
      POSTGRES_DB: mylibrary_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: